name             'sprout-osx-homebrew-taps'
maintainer       'Gabriel Gayan'
maintainer_email 'ggayan@comparaonline.com'
license          'MIT'
description      'Taps homebrew repositories'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-osx-base'
depends          'homebrew'
